site_name: GEOCOM Base de Datos Técnica

site_url: https://schweineorgel.github.io/geocom-kb/

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true

nav:
  - Inicio: index.md
  - Conceptos:
      - Constelaciones GNSS: conceptos/gnss/constelaciones.md
  - Procedimientos:
      - DJI:
          - Phantom 4 RTK:
              - Formateo Micro SD Phantom 4 RTK: procedimientos/dji/phantom-4-rtk/phantom4rtk-microsd-format.md
      - Trimble:
          - Prueba de Rendimiento de Radio: procedimientos/trimble/radio-thru-test.md
          - Colectoras:
              - Configuración FTP WMFTP: procedimientos/trimble/wmftp.md
  - Diagnósticos:
      - DJI:
          - Matrice 4 Enterprise:
              - Diagnóstico de Falla ESC 3: diagnosticos/dji/matrice4e/matrice4e-esc3.md
      - Trimble:
          - SX12:
              - SX12 no conecta por Wi-Fi después de actualizar a firmware S2.8.x: diagnosticos/trimble/sx12/sx12-falla-conexion-wifi.md
              
